### ISSUE TITLE
Errors in http://bluebrain.github.io/RTNeuron-3.0/python/gallery.html

### ISSUE THREAD

**Issue by alex4200** [BlueBrain/RTNeuron#9]
- In 'Getting Started': Not clear what the 'snapshot' function does:
  `rtneuron.snapshot_to_notebook(rtneuron.engine.views[0])`

 - In 'Getting Started' 7th code block I get  bunch of output that confused me and an error:
    ````In [5]: rtneuron.display_circuit(blueconfig, 6523)
   ...: # This function doesn't directly accept a dictionary for the attributes, it has to be
   ...: # an AttributeMap instead.
   ...: rtneuron.display_synapses(
   ...:     6523, attributes=rtneuron.AttributeMap({'color': [1, 1, 0, 1], 'radius': 3}))
   ...: rtneuron.snapshot_to_notebook(rtneuron.engine.views[0])
   ...: 
```
['/gpfs/bbp.cscs.ch/project/proj3/resources/circuits/ReleaseL2_fixed']
Trying to load blue config: /gpfs/bbp.cscs.ch/project/proj3/resources/circuits/ReleaseL2_fixed... done
132234 co::Connection 0x2aab44002130 state closed description NONE#0###0#default#: 3 MB out, 0 MB in
132234 co::Connection 0x2aab340059f0 state closed description ANON_PIPE#1024000###0#default#: 1 MB out, 4 MB in
132234 co::Connection 0x2aab3401da60 state closed description ANON_PIPE#1024000###0#default#: 4 MB out, 1 MB in
132335 co::Connection 0x2aab34003700 state closed description ANON_PIPE#1024000###0#default#: 2 MB out, 0 MB in
132335 co::Connection 0x2aab34003900 state closed description ANON_PIPE#1024000###0#default#: 0 MB out, 2 MB in
Error starting Servus client: Can't setup avahi client: Daemon not running
Error starting Servus client: Can't setup avahi client: Daemon not running
Error starting Servus client: Can't setup avahi client: Daemon not running
Error starting Servus client: Can't setup avahi client: Daemon not running
Creating 1 neurons
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Adding 1 neurons to the scene
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
  4863 Only unmerged synapse files found for /gpfs/bbp.cscs.ch/release/l2/2012.07.23/circuit/O1/merged_circuit/ncsFunctionalAllRecipePathways/nrn_positions.h5; consider using merged files for better performance.


 46718 No merged file found in "/gpfs/bbp.cscs.ch/release/l2/2012.07.23/circuit/O1/merged_circuit/ncsFunctionalAllRecipePathways" to build lookup index; loading data will be very slow
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: r2i3n0: task 0: Killed
Connection to r2i3n0.bbp.epfl.ch closed.```
```

 - in Meshes and models, fifth code block:
    `scene.addMesh(vertices, indices, colors=colors, attributes=attributes)`
     AttributeError: 'Scene' object has no attribute 'addMesh'

**Comment by hernando** [comment]
So far I have addressed 1, 3, 4, 5, 6 and 9. All the others that have to do with the simulation/circuit config will take longer. I wish there was a public dataset I could use instead.

**Comment by alex4200** [comment]
@hernando Item 9 does not yet seem to work. I still get the same error..

**Comment by hernando** [comment]
True, I didn't fully resolve it because blue.test is still not defined. You should be able to load some other configuration, however, I forgot to update the deployment. I'll get back to you when you can test again, should be done in a couple of hours.

**Comment by hernando** [comment]
You can try again now

**Comment by alex4200** [comment]
Hi,


I still get the same error when I follow the instructions...


Alex

________________________________

**Comment by hernando** [comment]
Number should now be resolved.

**Comment by hernando** [comment]
Sorry, it isn't I what confused by a build recipe used in CI that contains the test data. The recipe used in deployment doesn't contain it.
